#ifndef HERO_XIAO_ESP32S3_SENSE_CONFIG_H_
#define HERO_XIAO_ESP32S3_SENSE_CONFIG_H_

#include <driver/gpio.h>

// XIAO ESP32-S3 Sense integrated PDM microphone.
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_41
#define AUDIO_I2S_MIC_GPIO_CLK GPIO_NUM_42

// MAX98357A on XIAO D1/D3/D8.
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_2
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_4
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_7

// SH1107 128x128 OLED on XIAO D4/D5.
#define DISPLAY_SDA_PIN GPIO_NUM_5
#define DISPLAY_SCL_PIN GPIO_NUM_6
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 128
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_I2C_PRIMARY_ADDRESS 0x3c
#define DISPLAY_I2C_SECONDARY_ADDRESS 0x3d

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#endif  // HERO_XIAO_ESP32S3_SENSE_CONFIG_H_
